
name: test check.bats
on:
  push:
    branches:
      - main
    tags:
      - v1     
jobs:
  job_1:
    name: test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - name: test
      run: |
        git clone https://github.com/bats-core/bats-core.git -b v1.0.0 && cd bats-core && ./install.sh /usr/local
        make check
   
