
name: test check.bats
on:
  push:
    branches:
      - main
    tags:
      - v1     
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.2.1
          
      - name: test
        run: |
          make check
